openapi: 3.0.0
info:
  title: Wallet Service
  version: 1.0.0
servers:
  - url: http://localhost:3001
tags:
  - name: wallet
paths:
  /v1/balance:
    get:
      tags: [wallet]
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Current balance
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BalanceResponse"
        "401":
          description: Unauthorized
        "503":
          description: Wallet not provisioned
  /v1/transactions:
    get:
      tags: [wallet]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - in: query
          name: cursor
          schema:
            type: string
      responses:
        "200":
          description: Transactions list
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Transaction"
                  nextCursor:
                    type: string
                    nullable: true
        "401":
          description: Unauthorized
        "503":
          description: Wallet not provisioned
    post:
      tags: [wallet]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [type, amountMinor]
              properties:
                type:
                  type: string
                  enum: [credit, debit]
                amountMinor:
                  type: integer
                  minimum: 1
                description:
                  type: string
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionCreated"
        "401":
          description: Unauthorized
        "400":
          description: Validation error
        "409":
          description: Insufficient funds
        "503":
          description: Wallet not provisioned
  /v1/transactions/credit:
    post:
      tags: [wallet]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionCreate"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionCreated"
        "401":
          description: Unauthorized
        "400":
          description: Validation error
        "503":
          description: Wallet not provisioned
  /v1/transactions/debit:
    post:
      tags: [wallet]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionCreate"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionCreated"
        "401":
          description: Unauthorized
        "400":
          description: Validation error
        "409":
          description: Insufficient funds
        "503":
          description: Wallet not provisioned
components:
  schemas:
    TransactionCreate:
      type: object
      required: [amountMinor]
      properties:
        amountMinor:
          type: integer
          minimum: 1
        description:
          type: string
    TransactionCreated:
      type: object
      required: [id, status]
      properties:
        id:
          type: string
        status:
          type: string
          example: recorded
    Transaction:
      type: object
      required: [id, type, amountMinor, createdAt]
      properties:
        id:
          type: string
        type:
          type: string
          enum: [credit, debit]
        amountMinor:
          type: integer
        description:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
    BalanceResponse:
      type: object
      properties:
        balanceMinor:
          type: integer
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
